# Changes here will be overwritten by Copier
_commit: 5.0.2
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: diamhighlvlapps@diamond.ac.uk
author_name: High Level Apps
component_lifecycle: production
component_owner: group:default/high-level-apps
component_type: application
description: Python version of the BackUp and ResTore tool
distribution_name: pyburt
docker: true
docker_debug: false
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: pyburt
pypi: false
repo_name: pyburt
type_checker: mypy
