rhel7_job:
  tags:
    - rhel7
  script:
    - virtualenv --python dls-python venv
    - source venv/bin/activate
    - pip install pytest
    - pip install pytest-cov
    - pip install cothread
    - pip install pycodestyle
    - pip install pydocstyle
    - pip install mock
    - python -m pytest --cov=burt --cov-report term-missing --cov-fail-under 90 test
    - pycodestyle --show-source --show-pep8 burt
    - pydocstyle -e burt
